#ifndef __MOBILE_COMPILE_COFING_H__
#define __MOBILE_COMPILE_COFING_H__

#define NO_IRR_COMPILE_WITH_TERRAIN_NODE_
#define NO_IRR_COMPILE_WITH_OCTREE_NODE_
#define NO_IRR_COMPILE_WITH_VOLUME_LIGHT_NODE_
#define NO_IRR_COMPILE_WITH_WATER_SURFACE_NODE_
// #define NO_IRR_COMPILE_WITH_SKY_BOX_NODE_
// #define NO_IRR_COMPILE_WITH_SKY_DOME_NODE_

#define NO_IRR_COMPILE_WITH_SDL_DEVICE_
#define NO_IRR_COMPILE_WITH_CONSOLE_DEVICE_
#define NO_IRR_COMPILE_WITH_JOYSTICK_EVENTS_
//#define NO_IRR_COMPILE_WITH_XML_
#define NO_IRR_COMPILE_WITH_LEAK_HUNTER_
#define NO_IRR_COMPILE_WITH_PROFILING_
#define NO_IRR_COMPILE_WITH_DIRECTINPUT_JOYSTICK_
#define NO_IRR_COMPILE_WITH_DIRECT3D_8_
#define NO_IRR_COMPILE_WITH_DIRECT3D_9_
#define NO_IRR_COMPILE_WITH_OPENGL_
#define NO_IRR_COMPILE_WITH_OGLES1_
// #define NO_IRR_COMPILE_WITH_OGLES2_
#define NO_IRR_COMPILE_WITH_SOFTWARE_
#define NO_IRR_COMPILE_WITH_BURNINGSVIDEO_
#define NO_IRR_COMPILE_WITH_X11_
#define NO_IRR_LINUX_X11_VIDMODE_
#define NO_IRR_LINUX_X11_RANDR_
#define NO_IRR_LINUX_XCURSOR_
#define NO_IRR_COMPILE_WITH_GUI_
#define NO_IRR_WCHAR_FILESYSTEM
// #define NO_IRR_COMPILE_WITH_LIBJPEG_
// #define NO_IRR_USE_NON_SYSTEM_JPEG_LIB_
// #define NO_IRR_COMPILE_WITH_LIBPNG_
// #define NO_IRR_USE_NON_SYSTEM_LIB_PNG_
#define NO_IRR_D3D_NO_SHADER_DEBUGGING
#define NO_IRR_D3D_USE_LEGACY_HLSL_COMPILER
#define NO_IRR_COMPILE_WITH_CG_
// #define NO_IRR_COMPILE_WITH_IRR_SCENE_LOADER_
// #define NO_IRR_COMPILE_WITH_SKINNED_MESH_SUPPORT_
#define NO_IRR_COMPILE_WITH_B3D_LOADER_
#define NO_IRR_COMPILE_WITH_MS3D_LOADER_
#define NO_IRR_COMPILE_WITH_X_LOADER_
#define NO_IRR_COMPILE_WITH_OGRE_LOADER_
#define NO_IRR_COMPILE_WITH_IRR_MESH_LOADER_
#define NO_IRR_COMPILE_WITH_HALFLIFE_LOADER_
// #define NO_IRR_COMPILE_WITH_MD2_LOADER_
#define NO_IRR_COMPILE_WITH_MD3_LOADER_
//#define NO_IRR_COMPILE_WITH_3DS_LOADER_
#define NO_IRR_COMPILE_WITH_COLLADA_LOADER_
#define NO_IRR_COMPILE_WITH_CSM_LOADER_
#define NO_IRR_COMPILE_WITH_BSP_LOADER_
#define NO_IRR_COMPILE_WITH_DMF_LOADER_
#define NO_IRR_COMPILE_WITH_LMTS_LOADER_
#define NO_IRR_COMPILE_WITH_MY3D_LOADER_
// #define NO_IRR_COMPILE_WITH_OBJ_LOADER_
#define NO_IRR_COMPILE_WITH_OCT_LOADER_
#define NO_IRR_COMPILE_WITH_LWO_LOADER_
#define NO_IRR_COMPILE_WITH_STL_LOADER_
#define NO_IRR_COMPILE_WITH_PLY_LOADER_
#define NO_IRR_COMPILE_WITH_SMF_LOADER_
#define NO_IRR_COMPILE_WITH_IRR_WRITER_
#define NO_IRR_COMPILE_WITH_COLLADA_WRITER_
#define NO_IRR_COMPILE_WITH_STL_WRITER_
#define NO_IRR_COMPILE_WITH_OBJ_WRITER_
#define NO_IRR_COMPILE_WITH_PLY_WRITER_
// #define NO_IRR_COMPILE_WITH_BMP_LOADER_
// #define NO_IRR_COMPILE_WITH_JPG_LOADER_
#define NO_IRR_COMPILE_WITH_PCX_LOADER_
// #define NO_IRR_COMPILE_WITH_PNG_LOADER_
#define NO_IRR_COMPILE_WITH_PPM_LOADER_
#define NO_IRR_COMPILE_WITH_PSD_LOADER_
// #define NO_IRR_COMPILE_WITH_DDS_LOADER_
#define NO_IRR_COMPILE_WITH_DDS_DECODER_LOADER_
// #define NO_IRR_COMPILE_WITH_PVR_LOADER_
// #define NO_IRR_COMPILE_WITH_TGA_LOADER_
#define NO_IRR_COMPILE_WITH_WAL_LOADER_
#define NO_IRR_COMPILE_WITH_LMP_LOADER_
#define NO_IRR_COMPILE_WITH_RGB_LOADER_
// #define NO_IRR_COMPILE_WITH_BMP_WRITER_
#define NO_IRR_COMPILE_WITH_JPG_WRITER_
#define NO_IRR_COMPILE_WITH_PCX_WRITER_
#define NO_IRR_COMPILE_WITH_PNG_WRITER_
#define NO_IRR_COMPILE_WITH_PPM_WRITER_
#define NO_IRR_COMPILE_WITH_PSD_WRITER_
#define NO_IRR_COMPILE_WITH_TGA_WRITER_
#define NO__IRR_COMPILE_WITH_ZIP_ARCHIVE_LOADER_
#define NO_IRR_COMPILE_WITH_ZLIB_
#define NO_IRR_USE_NON_SYSTEM_ZLIB_
#define NO_IRR_COMPILE_WITH_ZIP_ENCRYPTION_
#define NO_IRR_COMPILE_WITH_BZIP2_
#define NO_IRR_USE_NON_SYSTEM_BZLIB_
#define NO_IRR_COMPILE_WITH_LZMA_
#define NO__IRR_COMPILE_WITH_MOUNT_ARCHIVE_LOADER_
#define NO__IRR_COMPILE_WITH_PAK_ARCHIVE_LOADER_
#define NO__IRR_COMPILE_WITH_NPK_ARCHIVE_LOADER_
#define NO__IRR_COMPILE_WITH_TAR_ARCHIVE_LOADER_
#define NO__IRR_COMPILE_WITH_WAD_ARCHIVE_LOADER_
#define NO_IRRLICHT_FAST_MATH
// #define NO__IRR_HAS_S64
#define NO_IRR_SCENEMANAGER_DEBUG

#endif // __MOBILE_COMPILE_COFING_H__